name: tests
on: push
jobs:
  run_tests:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
  uses: actions/checkout@v4.1.1
    - name: Setup Java JDK
  uses: actions/setup-java@v4.0.0
  with:
  java-version: 11
    - name: Cache Maven packages
  uses: actions/cache@74ed895d2add2dde989ad55ca039d6420de78144
  with:
  path: ~/.m2
  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
  restore-keys: ${{ runner.os }}-m2
    - name: Run tests with Maven
  run: mvn -B test --file pom.xml
